export const TYPE_COLORS = {
  APT_GROUP: '#ef4444',
  MALWARE: '#f59e0b',
  TOOL: '#eab308',
  CVE: '#a855f7',
  TECHNIQUE: '#3b82f6',
  COUNTRY: '#22c55e',
  INDUSTRY: '#14b8a6',
  PERSON: '#ec4899',
  CAMPAIGN: '#8b5cf6',
  ORGANIZATION: '#6b7280',
};

export const TYPE_NAMES = {
  APT_GROUP: 'APT组织',
  MALWARE: '恶意软件',
  TOOL: '工具',
  CVE: '漏洞',
  TECHNIQUE: '攻击技术',
  COUNTRY: '国家',
  INDUSTRY: '行业',
  PERSON: '人员',
  CAMPAIGN: '攻击活动',
  ORGANIZATION: '组织',
};

export const TYPE_GROUP = {
  APT_GROUP: 1, MALWARE: 2, TOOL: 3, CVE: 4,
  TECHNIQUE: 5, COUNTRY: 6, INDUSTRY: 7,
  PERSON: 8, CAMPAIGN: 9, ORGANIZATION: 10,
};

export const mockData = {
  nodes: [
    { id: "ENT_APT_GROUP_apt28_001", name: "APT28", type: "APT_GROUP", confidence: 0.97, description: "与俄罗斯GRU有关联的APT组织，又名Fancy Bear", properties: { origin_country: "Russia", active_years: "2007-2026", motivation: "espionage", aliases: ["Fancy Bear", "Sofacy", "Sednit"] } },
    { id: "ENT_APT_GROUP_lazarus_001", name: "Lazarus", type: "APT_GROUP", confidence: 0.96, description: "与朝鲜有关的APT组织，又名HIDDEN COBRA", properties: { origin_country: "North Korea", active_years: "2009-2026", aliases: ["HIDDEN COBRA"] } },
    { id: "ENT_APT_GROUP_kimsuky_001", name: "Kimsuky", type: "APT_GROUP", confidence: 0.94, description: "与朝鲜有关的APT组织，又名Black Banshee", properties: { origin_country: "North Korea", active_years: "2012-2026", aliases: ["Black Banshee"] } },
    { id: "ENT_MALWARE_lamehug_001", name: "LameHug", type: "MALWARE", confidence: 0.90, description: "APT28使用的后门恶意软件", properties: { platform: "Windows", type: "backdoor" } },
    { id: "ENT_MALWARE_xagent_001", name: "X-Agent", type: "MALWARE", confidence: 0.92, description: "APT28使用的多平台恶意软件框架", properties: { platform: "Windows, Android" } },
    { id: "ENT_MALWARE_wannacry_001", name: "WannaCry", type: "MALWARE", confidence: 0.91, description: "2017年全球爆发的勒索软件", properties: { platform: "Windows", type: "ransomware" } },
    { id: "ENT_MALWARE_babloy_001", name: "BabLoy", type: "MALWARE", confidence: 0.85, description: "Kimsuky使用的键盘记录器", properties: { platform: "Windows" } },
    { id: "ENT_CVE_cve2025_12345", name: "CVE-2025-12345", type: "CVE", confidence: 0.93, description: "Windows远程代码执行漏洞", properties: { cvss_score: 9.1, severity: "CRITICAL" } },
    { id: "ENT_CVE_cve2021_44228", name: "CVE-2021-44228", type: "CVE", confidence: 0.95, description: "Apache Log4j远程代码执行漏洞", properties: { cvss_score: 10.0 } },
    { id: "ENT_TECHNIQUE_t1566", name: "鱼叉式钓鱼附件", type: "TECHNIQUE", confidence: 0.96, description: "通过鱼叉式钓鱼邮件投递恶意附件(T1566)", properties: { tactic: "初始访问", mitre_id: "T1566" } },
    { id: "ENT_TECHNIQUE_t1203", name: "利用客户端漏洞", type: "TECHNIQUE", confidence: 0.94, description: "利用客户端软件中的漏洞执行代码(T1203)", properties: { tactic: "执行", mitre_id: "T1203" } },
    { id: "ENT_TECHNIQUE_t1059", name: "命令和脚本解释器", type: "TECHNIQUE", confidence: 0.93, description: "利用命令和脚本解释器执行代码(T1059)", properties: { tactic: "执行", mitre_id: "T1059" } },
    { id: "ENT_COUNTRY_russia_001", name: "Russia", type: "COUNTRY", confidence: 0.99, description: "俄罗斯", properties: { code: "RU" } },
    { id: "ENT_COUNTRY_nkorea_001", name: "North Korea", type: "COUNTRY", confidence: 0.99, description: "朝鲜", properties: { code: "KP" } },
    { id: "ENT_COUNTRY_ukraine_001", name: "Ukraine", type: "COUNTRY", confidence: 0.98, description: "乌克兰", properties: { code: "UA" } },
    { id: "ENT_COUNTRY_skorea_001", name: "South Korea", type: "COUNTRY", confidence: 0.98, description: "韩国", properties: { code: "KR" } },
    { id: "ENT_INDUSTRY_gov_001", name: "政府机构", type: "INDUSTRY", confidence: 0.95, description: "政府机关", properties: { sector: "public" } },
    { id: "ENT_INDUSTRY_finance_001", name: "金融行业", type: "INDUSTRY", confidence: 0.92, description: "银行和金融机构", properties: { sector: "financial" } },
    { id: "ENT_TOOL_metasploit_001", name: "Metasploit", type: "TOOL", confidence: 0.88, description: "渗透测试框架", properties: {} },
    { id: "ENT_CAMPAIGN_camp_001", name: "乌克兰网络攻击", type: "CAMPAIGN", confidence: 0.91, description: "2025年APT28针对乌克兰的攻击行动", properties: {} },
    { id: "ENT_CAMPAIGN_camp_002", name: "加密货币盗窃行动", type: "CAMPAIGN", confidence: 0.89, description: "Lazarus针对加密货币的攻击行动", properties: {} },
    { id: "ENT_ORGANIZATION_gru_001", name: "GRU", type: "ORGANIZATION", confidence: 0.93, description: "俄罗斯总参谋部情报总局", properties: {} },
    { id: "ENT_ORGANIZATION_mandiant_001", name: "Mandiant", type: "ORGANIZATION", confidence: 0.96, description: "知名网络安全公司", properties: {} },
  ],
  edges: [
    { id: "REL_apt28_lamehug", source: "ENT_APT_GROUP_apt28_001", target: "ENT_MALWARE_lamehug_001", type: "USES", label: "使用", confidence: 0.88 },
    { id: "REL_apt28_xagent", source: "ENT_APT_GROUP_apt28_001", target: "ENT_MALWARE_xagent_001", type: "USES", label: "使用", confidence: 0.92 },
    { id: "REL_apt28_cve2025", source: "ENT_APT_GROUP_apt28_001", target: "ENT_CVE_cve2025_12345", type: "EXPLOITS", label: "利用", confidence: 0.85 },
    { id: "REL_apt28_t1566", source: "ENT_APT_GROUP_apt28_001", target: "ENT_TECHNIQUE_t1566", type: "USES", label: "使用技术", confidence: 0.95 },
    { id: "REL_apt28_t1203", source: "ENT_APT_GROUP_apt28_001", target: "ENT_TECHNIQUE_t1203", type: "USES", label: "使用技术", confidence: 0.90 },
    { id: "REL_apt28_ukraine", source: "ENT_APT_GROUP_apt28_001", target: "ENT_COUNTRY_ukraine_001", type: "TARGETS", label: "瞄准", confidence: 0.93 },
    { id: "REL_apt28_gov", source: "ENT_APT_GROUP_apt28_001", target: "ENT_INDUSTRY_gov_001", type: "TARGETS", label: "瞄准", confidence: 0.91 },
    { id: "REL_apt28_gru", source: "ENT_APT_GROUP_apt28_001", target: "ENT_ORGANIZATION_gru_001", type: "ATTRIBUTED_TO", label: "归属于", confidence: 0.94 },
    { id: "REL_lazarus_wannacry", source: "ENT_APT_GROUP_lazarus_001", target: "ENT_MALWARE_wannacry_001", type: "DEVELOPS", label: "开发", confidence: 0.82 },
    { id: "REL_lazarus_log4j", source: "ENT_APT_GROUP_lazarus_001", target: "ENT_CVE_cve2021_44228", type: "EXPLOITS", label: "利用", confidence: 0.76 },
    { id: "REL_lazarus_finance", source: "ENT_APT_GROUP_lazarus_001", target: "ENT_INDUSTRY_finance_001", type: "TARGETS", label: "瞄准", confidence: 0.95 },
    { id: "REL_lazarus_nkorea", source: "ENT_APT_GROUP_lazarus_001", target: "ENT_COUNTRY_nkorea_001", type: "ATTRIBUTED_TO", label: "归属于", confidence: 0.95 },
    { id: "REL_kimsuky_babloy", source: "ENT_APT_GROUP_kimsuky_001", target: "ENT_MALWARE_babloy_001", type: "USES", label: "使用", confidence: 0.85 },
    { id: "REL_kimsuky_skorea", source: "ENT_APT_GROUP_kimsuky_001", target: "ENT_COUNTRY_skorea_001", type: "TARGETS", label: "瞄准", confidence: 0.94 },
    { id: "REL_kimsuky_t1566", source: "ENT_APT_GROUP_kimsuky_001", target: "ENT_TECHNIQUE_t1566", type: "USES", label: "使用技术", confidence: 0.90 },
    { id: "REL_kimsuky_nkorea", source: "ENT_APT_GROUP_kimsuky_001", target: "ENT_COUNTRY_nkorea_001", type: "ATTRIBUTED_TO", label: "归属于", confidence: 0.93 },
    { id: "REL_lazarus_kimsuky", source: "ENT_APT_GROUP_lazarus_001", target: "ENT_APT_GROUP_kimsuky_001", type: "AFFILIATED_WITH", label: "关联", confidence: 0.65 },
    { id: "REL_apt28_campaign", source: "ENT_CAMPAIGN_camp_001", target: "ENT_APT_GROUP_apt28_001", type: "ATTRIBUTED_TO", label: "归因于", confidence: 0.91 },
    { id: "REL_lazarus_campaign", source: "ENT_CAMPAIGN_camp_002", target: "ENT_APT_GROUP_lazarus_001", type: "ATTRIBUTED_TO", label: "归因于", confidence: 0.89 },
    { id: "REL_apt28_mandiant", source: "ENT_APT_GROUP_apt28_001", target: "ENT_ORGANIZATION_mandiant_001", type: "DISCOVERED_BY", label: "被发现", confidence: 0.90 },
  ],
};
